### ISSUE TITLE
Rations spoil instantly upon opening after a protracted campaign

### ISSUE THREAD

**Issue by TwelveEyes** [caligari87/Ugly-as-Sin#165] opened 2021-08-20 23:39 UTC
I'm not sure if this is intended behavior, but I've noticed in a long (talking many hours here) HD run save that every ration I picked up was always spoiled. I just thought this was bad luck until I unsealed fresh rations and watched their spoilage drop instantly from "basically fresh" through the intervening states into "clearly spoiled" in a second.

Looking at the check in `DoSpoilage()` I wonder if `level.time` (reset time on hub change) or `level.maptime` (reset time on map change) would be more appropriate instead of `level.totaltime` (no time reset)?
https://github.com/caligari87/Ugly-as-Sin/blob/64512469a272ad904c8da09cac2486a3a86080f4/hunger/module/consumable/consumable_misc.zsc#L50

Otherwise, I think after a game has gone on long enough, it seems at a certain point `level.totaltime` is always going to be greater than `UGCS_LASTSPOILTIME`.

**Comment by caligari87** [comment] 2021-08-21 00:48
I think the problem is actually that the last spoil time always starts at zero, even if the consumable is spawned several hours into a game. So basically all consumables are doing their spoilage checks based on the first tic of the game, even perfectly sealed ones. It just only becomes apparent several hours in, because that's roughly how long full spoilage can take.

I'll make some changes to when the `UGCS_LASTSPOILTIME` value is initialized, though I'll be working tonight and tomorrow so I'm not sure I'll be able to test it completely.

**Comment by caligari87** [comment] 2021-08-21 00:58
Pushed a change. Basically I initialize `UGCS_LASTSPOILTIME` to `-1` when the item is first spawned (unless it spawns opened) and treat that as "do not spoil". It gets set to `level.totaltime` when it's opened for the first time. This *should* alleviate the issue but I'm not able to fully test right now.

**Comment by TwelveEyes** [comment] 2021-08-21 01:04
> I think the problem is actually that the last spoil time always starts at zero, even if the consumable is spawned several hours into a game. So basically all consumables are doing their spoilage checks based on the first tic of the game, even perfectly sealed ones. It just only becomes apparent several hours in, because that's roughly how long full spoilage can take.

That makes sense.

Honestly, I didn't know if you did this on purpose. Something like the area has been so saturated by the Tyrant's twisted essence over time that food rots almost instantly on contact with it.

**Comment by caligari87** [comment] 2021-08-21 02:01
It's more for gameplay purposes 😅 since most games won't last more than a day or two and the engine shits itself at two weeks. But that's a good rationale!

I'll leave this open for a bit just in case, but I'll close it in a few days if nothing crops up.

**Comment by caligari87** [comment] 2021-09-01 16:45
Closing as no further reports are made

**Closed by caligari87** 2021-09-01 16:45 UTC
Labels: bug
